material-identity/CoA-schemas@main:
  - source: packages/generate-coa-pdf-template/dist/generateContent.js
    dest: generate-pdf.min.js

material-identity/EN10168-schemas@main:
  - source: packages/generate-en10168-pdf-template/dist/generateContent.js
    dest: generate-pdf.min.js
