material-identity/CoA-schemas@main:
  - source: dist/packages/generate-coa-pdf-template/generateContent.cjs
    dest: generate-pdf.min.js

material-identity/EN10168-schemas@main:
  - source: dist/packages/generate-en10168-pdf-template/generateContent.cjs
    dest: generate-pdf.min.js
