name: Schema-tools CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'renovate.json'
      - '**/package-lock.json'
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README.md'
      - 'renovate.json'
      - 'openapi.json'
      - '**/package-lock.json'
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install GraphicsMagick
        run: sudo apt-get install -y ghostscript graphicsmagick

      - name: Install dependencies
        run: npm run bootstrap

      # - name: Scan dependencies
      #   run: npm run scan:deps

      - name: Build packages
        run: npm run build

      # update to only run on PR, not push to main
      - name: Commit changes to dist/generateContents.js
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update minified generateContents.js [ci]'
          file_pattern: packages/generate-coa-pdf-template/dist/generateContent.js packages/generate-en10168-pdf-template/dist/generateContent.js

      # TODO: only run tests on changed code
      - name: Run Karma tests
        run: npm run test:browser

      - name: Run Jest tests
        run: npm run test:cov
        env:
          CI: true

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
          retention-days: 2

  scan:
    needs: setup-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Retrieve coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: ./coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_URL: ${{ secrets.SONAR_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
