name: Schema-tools CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'renovate.json'
      - '**/package-lock.json'
      - 'utils/**'
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README.md'
      - 'renovate.json'
      - 'openapi.json'
      - '**/package-lock.json'
      - 'utils/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
  NX_DISTRIBUTED_TASK_EXECUTION: false

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.OS }}-node--${{ matrix.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-node-${{ matrix.node-version }}-npm

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: set-sha
        uses: nrwl/nx-set-shas@v3

      - name: Install GraphicsMagick
        run: sudo apt-get update && sudo apt-get install -y ghostscript graphicsmagick

      - name: Install dependencies
        run: npm ci

      # - name: Scan dependencies
      #   run: npm run scan:deps

      - name: Build packages
        run: npm run build:affected

      - name: Run Jest tests
        run: npm run test:cov:affected
        env:
          CI: true

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage
          retention-days: 2

  # Added to avoid running Danger and pdfGenerator twice
  pdf-generator:
    runs-on: ubuntu-latest
    needs: setup-and-test
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.OS }}-node--${{ matrix.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-node-${{ matrix.node-version }}-npm

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: set-sha
        uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build:affected

      - name: Extract branch name
        id: extract-branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Danger
        if: steps.extract-branch.outputs.branch != 'main'
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add, commit and push changes to dist/**/generateContents.cjs
        if: steps.extract-branch.outputs.branch != 'main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update minified generateContents.cjs [skip ci]'
          file_pattern: dist/packages/**/generateContent.cjs
          add_options: '-f'

  scan:
    needs: setup-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get current version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Retrieve coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: ./coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_URL: ${{ secrets.SONAR_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.package-version.outputs.current-version }}

  fossa:
    needs: setup-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: FOSSA analysis
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          branch: ${{ env.BRANCH_NAME }}

      - name: FOSSA tests
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
